### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by anwilkie**
# What and why?
Updating dependencies to resolve dependabot alerts

# How to test?
Do `pipenv install`, then `pipenv graph`, and check the following dependencies have upgraded:

- Flask-Cors (>=4.0.2)
- setuptools (>=70.0.0)
- gunicorn (>=22.0.0)
- urllib3 (>=2.2.2)
- requests (>=2.32.0)
- jinja2 (>=3.1.4)
- aiohttp (>=3.10.2)
- idna (>=3.7)
- certifii (>=2024.07.04)
- werkzeug (>=3.0.3)

Deploy, run tests, and make sure reporting service still works.

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-1304)

### CODE REVIEW

**Review by pricem14pc — CHANGES_REQUESTED** [review]
We have unsigned bot commits
- Include the GHA changes from the PR branch https://github.com/ONSdigital/rm-reporting/pull/123 in this PR branch and close that other PR
- revert the Chart.yaml bump on this PR branch
- commit the above changes to this PR branch
- ensure the bot re-bump is signed

However, the library version bumps all surpass the open dependabot PRs which is good. And manual testing of downloading a response chasing report was successful.

**Review by pricem14pc — APPROVED** [review]

**Review by matthew-robinson-ons — APPROVED** [review]
Changes look good and report is downloadable after changes

**Pull request closed without merging**
